export const SIDEBAR_WIDTH = 300;

export const SIDEBAR_ANIMATION_DURATION = 1;

export const SIDEBAR_HEIGHT_WITHOUT_LOGO = 803;

export const SIDEBAR_TITLE_HEIGHT = 60;

export const SIDEBAR_GAP_SIZE = 20;

export const CREATE_BOARD_BUTTON_HEIGHT = 48;

export const SWITCH_AND_HIDE_SIDEBAR_BUTTON_CONTAINER_HEIGHT = 116;
